title: Juan Lezama
description: Activist, Kabbalah enthusiast, Starup entrepreneur # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/juanlezamaofficial.github.io" # the subpath of your site, e.g. /blog
url: "https://juanlezamaofficial.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: juanlezama #if your site has a twitter account, enter it here

# Author Settings
author: Juan Lezama # add your name
author-img: juan-lezama.jpg # add your photo
about-author: Activist, Kabbalah enthusiast, Starup entrepreneur. # add description
social-twitter: juanlezama # add your Twitter handle
social-facebook: juanlezamaofficial # add your Facebook handle
social-github: juanlezamaofficial # add your Github handle
social-linkedin: https://www.linkedin.com/in/juanlezama # add your Linkedin handle
social-email: juanlezama.info.ve@gmail.com # add your Email address

# Disqus
discus-identifier: juanlezamaofficial # add your discus identifier

# Tracker
analytics: UA-120798446-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

theme: jekyll-theme-cayman
